### PR TITLE
Front and backend changes

### PR DESCRIPTION
**Pull request by Aide-C**
I added flask-login to auth_services.py to have user sessions. This will stop users from manipulating URL to get to home or generation pages without logging in. Also, did an aesthetic changes to home page to look like login and signup pages. I still need to add and connect log out button. 

## Summary by CodeRabbit

- **New Features**
  - Implemented user authentication in the app, allowing for login and logout functionalities.
  - Enhanced navigation within the app based on user authentication status.

- **Bug Fixes**
  - Improved form alignment and styling in the Home component without altering its functionality.

- **Chores**
  - Updated backend dependencies to include necessary libraries for user authentication.

### CODE REVIEW

**Comment by Aide-C** [comment]
I'm pretty sure this is just styling issues with my code but I'm not sure someone double check. 
When I checked it was just a bunch of "line too long" and "blank line" errors.

**Comment by Zfreeman24** [comment]
Does the code work? If it does I'll approve it.

**Comment by Zfreeman24** [comment]
Also I didn't check but if you made any changes to how the code is ran, make sure to add that into the README

**Comment by Zfreeman24** [comment]
And yeah, usually in a corporate setting they'd require those styling issues to be fixed... but because of time constraints it won't be worth it to address.

**Pull request merged**
